repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.14
    hooks:
    -   id: ruff
        args: [--fix]
        exclude: ^problems/
    -   id: ruff-format
        exclude: ^problems/

-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.350
    hooks:
    -   id: pyright
        exclude: ^problems/
